---
version: '3.8'

services:
  db:
    container_name: users_pgsql
    image: postgres:10.6
    command: -c fsync=off -c full_page_writes=off
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
      timeout: 1s
      retries: 15
      start_period: 5s
  app:
    container_name: application
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      FLASK_ENV: development
    depends_on:
      db:
        condition: service_healthy


